version: '3.6'
services:
    server:
        build: 
          context: "./backend"
          args:
            - APP_SERVER_PORT=${APP_SERVER_PORT}
        ports:
            - "${APP_SERVER_PORT}:80"
        environment: 
            - FLASK_ENV=${DEV_ENV}
            - APP_SERVER_PORT=${APP_SERVER_PORT}
        volumes:
            - "./backend:/app"
        expose:
            - ${APP_SERVER_PORT}
            - ${WEB_SOCKET_PORT}

    client:
        build:
          context: "./frontend"
        expose:
          - ${REACT_APP_PORT}
        volumes:
          - './frontend:/app'
          - '/app/node_modules'
        ports:
          - "${REACT_APP_PORT}:3000"
        links:
          - server
        environment:
          - NODE_ENV=${DEV_ENV}
          - REACT_APP_PORT=${REACT_APP_PORT}
        command: npm run start