version: '3.6'
services:
    server:
        build: 
          context: "./backend"
          dockerfile: Dockerfile
          args:
            - SERVER_PORT=${SERVER_PORT}
        ports:
            - "${SERVER_PORT}:80"
            - "${WEB_SOCKET_PORT}:${WEB_SOCKET_PORT}"
        environment: 
            - FLASK_ENV=${DEV_ENV}
            - SERVER_PORT=${SERVER_PORT}
        volumes:
            - "./backend:/app"
        expose:
            - ${SERVER_PORT}

    client:
        build:
          context: "./frontend"
          dockerfile: Dockerfile-prod
        expose:
          - ${REACT_APP_PORT}
        volumes:
          - './frontend:/app'
          - '/app/node_modules'
        ports:
          - "${REACT_APP_PORT}:80"
        links:
          - server
        environment:
          - NODE_ENV=${DEV_ENV}
          - REACT_APP_PORT=${REACT_APP_PORT}