STACK = "stack"
QUEUE = "queue"
PRIORITY_QUEUE = "priority_queue"



# Distributions

BETA = "beta"
BINOMIAL = "binomial"
CHISQUARE = "chisquare"
DIRICHLET ="dirichlet"
EXPONENTIAL = "exponential"
F = "f"
GAMMA = "gamma"
GEOMETRIC = "geometric"
GUMBEL = "gumbel"
HYPERGEOMETRIC = "hypergeometric"
LAPLACE = "laplace"
LOGISTIC = "logistic"
LOGNORMAL = "lognormal"
LOGSERIES = "logseries"
MULTINOMIAL = "multinomial"
MULTIVARIATE_NORMAL = "multivariate_normal"
NEGATIVE_BINOMIAL = "negative_binomial"
NONCENTRAL_CHISQUARE = "noncentral_chisquare"
NONCENTRAL_F = "noncentral_f"
NORMAL = "normal"
PARETO = "pareto"
POISSON = "poisson"
POWER = "power"
RAYLEIGH = "rayleigh"
STANDARD_CAUCHY = "standard_cauchy"
STANDARD_EXPONENTIAL = "standard_exponential"
STANDARD_GAMMA = "standard_gamma"
STANDARD_NORMAL = "standard_normal"
STANDARD_T = "standard_t"
TRIANGULAR = "triangular"
UNIFORM = "uniform"
VONMISSES = "vonmises"
WALD = "wald"
WEIBULL = "weibull"
ZIPF = "zipf"