FROM python:3.6-slim
COPY . /app
WORKDIR /app


RUN apt-get update && apt-get install -y build-essential python3-dev
RUN pip3 install wheel
RUN pip3 install -U flask uwsgi

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV FLASK_APP=./main.py

CMD uwsgi main

