FROM python:3.6-slim
COPY . /app
WORKDIR /app

RUN apt-get clean \
    && apt-get -y update


RUN apt-get -y install nginx \
    && apt-get -y install python3-dev \
    && apt-get -y install build-essential

RUN pip install -r requirements.txt --src /usr/local/src

ENV LC_ALL=C.UTF-8
ENV LANG=C.UTF-8
ENV FLASK_APP=./main.py


ENTRYPOINT ["sh", "./nginx.sh"]
